version: '3'
services:
    redis:
        image: redis
    register:
        build: ./register
        depends_on:
          - event-store
        environment:
          - TEST=true
        ports:
          - 3001:3001
    user-list:
        build: ./user_list
        depends_on:
          - event-store
        environment:
          - TEST=true
        ports:
          - 3002:3002
    event-store:
        build: ./event_store
        environment:
          - TEST=true
        depends_on:
          - redis
        ports:
          - 3000:3000
