apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    io.kompose.service: user-list
  name: user-list
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: user-list
    spec:
      containers:
      - image: user-list
        name: user-list
        ports:
        - containerPort: 3002
        resources: {}
      restartPolicy: Always
status: {}
